Threshold By Plane Configurables
DUNE-DAQ/daqconf pull request #455
Opened 2024-05-07 11:36 UTC by aeoranday

Configurables PR for TPG threshold by plane implementation in [fdreadoutlibs](https://github.com/DUNE-DAQ/fdreadoutlibs/pull/177).

Should `configs/daqconf_full_config.json` and `configs/daqconf_with_tpg.json` also reflect these changes? Leaving `<plane>_threshold` out of a `daqconf.json` will result in that plane defaulting to `tpg_threshold`, so I can see it going with or without.

2024-05-08 12:51 UTC, alessandrothea requested changes

2024-05-08 12:51 UTC, alessandrothea commented on python/daqconf/apps/readout_gen.py
>                          tpg_threshold = cfg.tpg_threshold,
Remove?

2024-05-08 12:51 UTC, alessandrothea commented on python/daqconf/apps/readout_gen.py
> +                        collection_threshold = cfg.collection_threshold,
prefix `tpg_`

2024-05-09 09:05 UTC, aeoranday commented
Latest commit made the word choice changes to match what is used in `detchannelmaps`. Configs and variables now refer to planes 0, 1, and 2 instead of induction 1, induction 2, and collection. Also prefixed with `tpg_`.

2024-05-13 13:32 UTC, alessandrothea approved these changes

2024-05-14 16:35 UTC, merged